version: '3.7'

services:
  app:
    image: 127.0.0.1:5000/chitchat:0.1.9
    ports:
      - 80:4000
    entrypoint: bin/chitchat start
    networks:
      - chitchat
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip

networks:
  chitchat:
    driver: overlay
    attachable: true
