version: '3.7'

services:
  app:
    image: 127.0.0.1:5000/chitchat:0.2.0
    ports:
      - 80:4000
    entrypoint: bin/chitchat start
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
